# Generated by Django 5.1.3 on 2025-02-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=64)),
                ('home', models.CharField(max_length=16)),
                ('apartment', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
