# Generated by Django 5.1.3 on 2025-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kaspi_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
