# Generated by Django 5.1.2 on 2024-11-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoodie', models.CharField()),
                ('zip_hoodie', models.CharField()),
                ('t_shirt', models.CharField()),
                ('book', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField()),
                ('product_image', models.ImageField(default='media/product_images/default_product_image.png', upload_to='product_images')),
                ('product_description', models.CharField()),
                ('product_count', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
        ),
    ]
