# Generated by Django 5.1.2 on 2024-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='book',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='hoodie',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='t_shirt',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='zip_hoodie',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='category', max_length=32),
        ),
    ]
