# Generated by Django 5.1.3 on 2025-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(default='S', max_length=2),
        ),
    ]
